matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: 3.6
    - os: linux
      dist: bionic
      language: python
      python: 3.7
    - os: osx            # python 3.7
      language: generic
      osx_image: xcode11

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y libhunspell-dev hunspell-en-us; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade python  ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hunspell; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://downloads.sourceforge.net/project/wordlist/speller/2018.04.16/hunspell-en_US-2018.04.16.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fwordlist%2Ffiles%2Fspeller%2F2018.04.16%2Fhunspell-en_US-2018.04.16.zip%2Fdownload%3Fuse_mirror%3Dpilotfiber&ts=; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; unzip hunspell-en_US-2018.04.16.zip -d /Library/Spelling/; fi
install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install coverage; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install coverage; fi

script:
  - coverage run --source generativepoetry setup.py test --verbose

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install coveralls; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install coveralls; fi
  - coveralls  # send coverage to coveralls.io

after_script:
  - coverage report                     # display coverage report on command line
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then pip install pycodestyle pyflakes; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then pip install pycodestyle pyflakes; fi
  - pyflakes . | tee >(wc -l)           # static analysis
  - pycodestyle --statistics --count .  # static analysis