language: python

matrix:
  include:
    - python: 3.6
      os: linux
      dist: bionic
    - python: 3.7
      os: linux
      dist: bionic
    - os: osx            # python 3.7
      python: generic
      osx_image: xcode11

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y libhunspell-dev hunspell-en-us; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade python  ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hunspell; fi

install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install coverage; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install -r requirements.txt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install coverage; fi

script:
  - coverage run --source generativepoetry setup.py test --verbose

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install coveralls; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install coveralls; fi
  - coveralls  # send coverage to coveralls.io

after_script:
  - coverage report                     # display coverage report on command line
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then pip install pycodestyle pyflakes; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] then pip install pycodestyle pyflakes; fi
  - pyflakes . | tee >(wc -l)           # static analysis
  - pycodestyle --statistics --count .  # static analysis