language: python

python:
  - "3.6"

matrix:
  include:
    - python: 3.7
      os: linux
      dist: bionic
    - python: 3.6
      os: linux
      dist: bionic
    - os: osx
      env: PYTHON=37
    - os: osx
      env: PYTHON=36

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hunspell; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y libhunspell-dev hunspell-en-us; fi

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source generativepoetry setup.py test --verbose

after_success:
  - pip install coveralls
  - coveralls  # send coverage to coveralls.io

after_script:
  - coverage report                     # display coverage report on command line
  - pip install pycodestyle pyflakes
  - pyflakes . | tee >(wc -l)           # static analysis
  - pycodestyle --statistics --count .  # static analysis